/*
* Copyright 2025 NXP
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#ifndef P3H2X4X_CONFIG_H_
#define P3H2X4X_CONFIG_H_

uint8_t tp_mode[I3C_HUB_TP_MAX_COUNT] = {
		 I3C_HUB_TP_MODE_SMBUS,
		 I3C_HUB_TP_MODE_SMBUS,
		 I3C_HUB_TP_MODE_I3C,
		 I3C_HUB_TP_MODE_I3C,
		 I3C_HUB_TP_MODE_NOT_SET,
		 I3C_HUB_TP_MODE_NOT_SET,
		 I3C_HUB_TP_MODE_NOT_SET,
		 I3C_HUB_TP_MODE_NOT_SET
};

uint8_t tp_pullup[I3C_HUB_TP_MAX_COUNT] = {
		I3C_HUB_TP_PULLUP_ENABLED,
		I3C_HUB_TP_PULLUP_ENABLED,
		I3C_HUB_TP_PULLUP_ENABLED,
		I3C_HUB_TP_PULLUP_ENABLED,
		I3C_HUB_TP_PULLUP_DISABLED,
		I3C_HUB_TP_PULLUP_DISABLED,
		I3C_HUB_TP_PULLUP_DISABLED,
		I3C_HUB_TP_PULLUP_DISABLED
};
uint8_t tp_ibi_config[I3C_HUB_TP_MAX_COUNT] = {
		I3C_HUB_IBI_DISABLED,
		I3C_HUB_IBI_DISABLED,
		I3C_HUB_IBI_DISABLED,
		I3C_HUB_IBI_DISABLED,
		I3C_HUB_IBI_DISABLED,
		I3C_HUB_IBI_DISABLED,
		I3C_HUB_IBI_DISABLED,
		I3C_HUB_IBI_DISABLED
};

/*MACROS to set different hub and tp config*/
#define I3C_HUB_CP0_LDO_CONFIG					I3C_HUB_LDO_DISABLED
#define I3C_HUB_CP1_LDO_CONFIG					I3C_HUB_LDO_DISABLED
#define I3C_HUB_TP0145_LDO_CONFIG				I3C_HUB_LDO_DISABLED
#define I3C_HUB_TP2367_LDO_CONFIG				I3C_HUB_LDO_DISABLED
#define I3C_HUB_CP0_LDO_VOLT					I3C_HUB_LDO_VOLT_1_8V
#define I3C_HUB_CP1_LDO_VOLT					I3C_HUB_LDO_VOLT_1_8V
#define I3C_HUB_TP0145_LDO_VOLT					I3C_HUB_LDO_VOLT_1_8V
#define I3C_HUB_TP2367_LDO_VOLT					I3C_HUB_LDO_VOLT_1_8V
#define I3C_HUB_TP0145_PULLUP					I3C_HUB_TP_PULLUP_1000R
#define I3C_HUB_TP2367_PULLUP					I3C_HUB_TP_PULLUP_1000R
#define I3C_HUB_CP0_IO_STRENGTH					I3C_HUB_IO_STRENGTH_20_OHM
#define I3C_HUB_CP1_IO_STRENGTH					I3C_HUB_IO_STRENGTH_20_OHM
#define I3C_HUB_TP0145_IO_STRENGTH				I3C_HUB_IO_STRENGTH_20_OHM
#define I3C_HUB_TP2367_IO_STRENGTH              I3C_HUB_IO_STRENGTH_20_OHM
#define I3C_HUB_TP_MODE(x)    					tp_mode[x]
#define I3C_HUB_TP_PULLUP(x)    				tp_pullup[x]
#define I3C_HUB_TP_IBI_CONFIG(x)    			tp_ibi_config[x]

#define I3C_HUB_DEV_CONF						0x13
#define I3C_HUB_IO_STRENGTH			        	0x14
#define TP0145_IO_STRENGTH_MASK					0x03
#define TP0145_IO_STRENGTH(x)					(((x) << 0) & TP0145_IO_STRENGTH_MASK)
#define TP2367_IO_STRENGTH_MASK					0x0C
#define TP2367_IO_STRENGTH(x)					(((x) << 2) & TP2367_IO_STRENGTH_MASK)
#define CP0_IO_STRENGTH_MASK					0x30
#define CP0_IO_STRENGTH(x)						(((x) << 4) & CP0_IO_STRENGTH_MASK)
#define CP1_IO_STRENGTH_MASK					0xC0
#define CP1_IO_STRENGTH(x)						(((x) << 6) & CP1_IO_STRENGTH_MASK)

#define I3C_HUB_VCCIO_LDO_CONF					0x16
#define CP0_VCCIO_LDO_VOLTAGE_MASK				0x03
#define CP0_VCCIO_LDO_VOLTAGE(x)				(((x) << 0) & CP0_VCCIO_LDO_VOLTAGE_MASK)
#define CP1_VCCIO_LDO_VOLTAGE_MASK				0x0C
#define CP1_VCCIO_LDO_VOLTAGE(x)				(((x) << 2) & CP1_VCCIO_LDO_VOLTAGE_MASK)
#define TP0145_VCCIO_LDO_VOLTAGE_MASK			0x30
#define TP0145_VCCIO_LDO_VOLTAGE(x)				(((x) << 4) & TP0145_VCCIO_LDO_VOLTAGE_MASK)
#define TP2367_VCCIO_LDO_VOLTAGE_MASK			0xC0
#define TP2367_VCCIO_LDO_VOLTAGE(x)				(((x) << 6) & TP2367_VCCIO_LDO_VOLTAGE_MASK)

#define I3C_HUB_LDO_AND_PULLUP_CONF				0x19
#define LDO_ENABLE_DISABLE_MASK					0x0F
#define CP0_EN_LDO				        		0x01
#define CP1_EN_LDO				        		0x02
#define TP0145_EN_LDO				    		0x04
#define TP2367_EN_LDO				    		0x08

#define  TP0145_PULLUP_CONF_MASK				0xC0
#define  TP0145_PULLUP_CONF(x)					(((x) << 6) & TP0145_PULLUP_CONF_MASK)
#define  TP2367_PULLUP_CONF_MASK				0x30
#define  TP2367_PULLUP_CONF(x)					(((x) << 4) & TP2367_PULLUP_CONF_MASK)

/*Target port control registers*/
#define  TPn_NET_CON(n)				        	(1<<n)

#define I3C_HUB_TP_IO_MODE_CONF					0x17
#define I3C_HUB_TP_SMBUS_AGNT_EN				0x18
#define TPn_SMBUS_MODE_EN(n)					(1<<n)
#define TPn_I2C_MODE_EN(n)				        (1<<n)

#define I3C_HUB_TP_GPIO_MODE_EN					0x1E
#define  TPn_GPIO_MODE_EN(n)					(1<<n)
#define  TPn_PULLUP_EN(n)			       		(1<<n)
#define TPn_IBI_EN(n)							(1<<n)
#define CONTROLLER_PORT_MUX_REQ					0x01

#endif /* P3H2X4X_CONFIG_H_ */
